### PR TITLE
Update cleanslate.css to include path, polygon

### PR DESCRIPTION
**Pull request by kkotobi**
Right now clean slate is missing declarations for `path` and `polygon` this change adds them.

### CODE REVIEW

**Comment by ddelrio1986** [comment]
Is anyone able to take a peek at this PR?

**Comment by premasagar** [comment]
Thanks for this. Currently, Cleanslate is just an HTML reset stylesheet. It does reset root `svg` elements as a part of an HTML page, but it doesn't affect any child SVG elements.

The CSS properties in the stylesheet are HTML-centric CSS properties. Some properties affect both HTML and SVG elements, but most do not. The stylesheet doesn't cover even the basics of SVG style resetting, such as reverting `color` to `black` or `fill` to either `black` or `none`, depending on the element.

There is a case for a reset stylesheet for SVG. Perhaps it would be an additional, optional stylesheet.

Is there a specific problem with `path` and `polygon` elements that you wanted to address?

**Comment by kkotobi** [comment]
I'm currently using  svg(s) which have path & polygon properties and, in some cases there's already a global definition for `path` or `polygon` using !important in the general css rules which then overrides the style inside the svg. Thank you for your response 😄

**Comment by kkotobi** [comment]
@premasagar Just wanted to see if you had a chance to look over my reply, if this change is something that's outside the scope of this library I can close the PR. Thanks

**Pull request closed without merging**
